image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build the docker image:
  stage: build
    script:
      - "docker build --"

  artifacts:
    paths:
      - build/


test the docker image:
  stage: test
    script:
      - "Testing Docker"

deploy the docker image:
  stage: deploy
    script:
      - "Deployed successfully"