image: docker:latest

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t angular-cicd-crud .
    - docker run -d -p 80:80 angular-cicd-crud
