image: docker:latest

services:
  - docker:dind

stages:
  - build
  # - test
  # - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest

build the docker image:
  stage: build
    script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker logout

#   artifacts:
#     paths:
#       - build/


# test the docker image:
#   stage: test
#     script:
#       - "Testing Docker"

# deploy the docker image:
#   stage: deploy
#     script:
#       - "Deployed successfully"