image:
  name: amazon/aws-cli
  entrypoint: [""]

services:
  - docker:dind

stages:
  - build
  - test
  - review
  # - dast
  - deploy
  # - production
  # - cleanup12

before_script:
  - amazon-linux-extras install docker
  - docker info
  - aws --version
  - docker --version

variables:
  # AWS_DEFAULT_REGION: ap-south-1
  DOCKER_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com #<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com
  # DOCKER_REPOSITORY: angular-cicd #<ECR_REPOSITORY_NAME>
  DOCKER_IMAGE_NAME: angular-cicd #<IMAGE_NAME>
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID  # Define these environment variables in your GitLab CI/CD settings
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  DOCKER_HOST: tcp://docker:2375
  TASK_DEFINTION_NAME: angular-cicd-task
  CLUSTER_NAME: angular-cicd-cluster
  SERVICE_NAME: angular-cicd-service


Publishing_to_AWS_ECR:
  stage: build
  # image:
  #  name: amazon/aws-cli
  #  entrypoint: [""]
  # services:
  #   - docker:dind
  # before_script:
  #   - amazon-linux-extras install docker
  #   - aws --version
  #   - docker --version
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - echo "Building image..."
    - docker build -t "$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA" .
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$DOCKER_REGISTRY"
    - echo "Pushing image..."
    - docker push "$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
      # Deploy to ECS (you will need to customize these commands based on your ECS setup)
    # - aws ecs update-service --cluster <ECS_CLUSTER_NAME> --service <ECS_SERVICE_NAME> --force-new-deployment


      # Optionally, clean up old Docker images to save space on GitLab Runner
    # - docker system prune -af
    - docker logout

Tseting_stage_1:
  stage: test
  script:
    - echo "Tested stage 1 successfully"

Testing_stage_2:
  stage: test
  script:
    - echo "Tested stage 2 successfully"

Review_stage:
  stage: review
  script: 
    - echo "Review stage successfull"


deploying_to_AWS_ECS:
  stage: deploy
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$DOCKER_REGISTRY"
    - docker pull "$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - aws ecs describe-task-definition --region ${AWS_DEFAULT_REGION} --task-definition ${TASK_DEFINTION_NAME}
    # - docker tag "$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$DOCKER_REGISTRY/$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"

    # Deploy to ECS (you will need to customize these commands based on your ECS setup)
    - aws ecs update-service --region ${AWS_DEFAULT_REGION} --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME}  --task-definition ${TASK_DEFINTION_NAME} --force-new-deployment
    # - aws logs describe-log-groups --log-group-name-prefix "/ecs/angular-cicd-cluster"
    # - aws logs describe-log-streams --log-group-name "/ecs/angular-cicd-cluster/angular-cicd"
    # - aws logs get-log-events --log-group-name "/ecs/angular-cicd-cluster/angular-cicd" --log-stream-name angular-cicd-log

    # Optionally, clean up old Docker images to save space on GitLab Runner
    - docker system prune -af
    - docker logout
