image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker info

variables:
  DOCKER_REGISTRY: https://index.docker.io/v1/
  DOCKER_REPOSITORY: satyam0999  # Replace with your Docker Hub username
  DOCKER_IMAGE_NAME: angular-cicd-crud

build:
  stage: build
  script:
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin "$DOCKER_REGISTRY"
    - docker build -t "$DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA" .
    - docker push "$DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    # - docker logout

test:
  stage: test
  image: node

  before_script:
   - echo -n "Running docker build successfully"
  script:
   - npm install
   - npm test

deploy_to_production:
  stage: deploy
  image: node
  before_script:
    - mkdir -p ~/.ssh
    - echo -n "$
  script:
    - kubectl apply -f deployment.yaml # Use the appropriate command for your orchestration tool
  only:
    - master # Define when this job should run (e.g., only on the master branch)