image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build the docker image:
  stage: build
    script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA

#   artifacts:
#     paths:
#       - build/


# test the docker image:
#   stage: test
#     script:
#       - "Testing Docker"

# deploy the docker image:
#   stage: deploy
#     script:
#       - "Deployed successfully"